<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.1.0</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\jaytwo.DistributedLocks\jaytwo.DistributedLocks.csproj" />
    <PackageReference Include="RedLock.net" Version="2.3.2" />
  </ItemGroup>

</Project>
