services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - 45432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  mysql:
    image: mysql:latest
    restart: always
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "43306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass redpass
    ports:
      - "46379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redpass", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
