<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.DistributedLocks\jaytwo.DistributedLocks.csproj" />
    <ProjectReference Include="..\..\src\jaytwo.DistributedLocks.Postgres\jaytwo.DistributedLocks.Postgres.csproj" />
    <ProjectReference Include="..\..\src\jaytwo.DistributedLocks.MySql\jaytwo.DistributedLocks.MySql.csproj" />
    <ProjectReference Include="..\..\src\jaytwo.DistributedLocks.SqlServer\jaytwo.DistributedLocks.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\jaytwo.DistributedLocks.RedLock\jaytwo.DistributedLocks.RedLock.csproj" />
  </ItemGroup>

</Project>
