<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jakegough-jaytwo/jaytwo.DistributedLocks</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="jaytwo.DistributedLocks.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jaytwo.DistributedLocks\jaytwo.DistributedLocks.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.*" />
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.*" />
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

</Project>
